[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.0-dev-2025-12-25.6017"
repository = "https://github.com/jeremyBanks/jeb"
edition = "2024"
license = "MIT OR Apache-2.0"
include = ["**/*.rs", "**/*.toml", "**/*.lock", "**/*.md", "**/LICENSE*", "!.*"]

[profile.small]
inherits = "release"
lto = true
opt-level = "z"
codegen-units = 1
strip = true
split-debuginfo = "packed"
panic = "abort"
