[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.0-dev-2025-12-26.7705"
repository = "https://github.com/jeremyBanks/jeb"
description = "(part of https://crates.io/crates/jeb)"
keywords = []
categories = []
edition = "2024"
license = "MIT OR Apache-2.0"
include = ["**/*.rs", "**/*.toml", "**/*.lock", "**/*.md", "**/LICENSE*", "!.*"]

[profile.dev.package.backtrace]
opt-level = 3

[profile.small]
inherits = "release"
lto = true
opt-level = "z"
codegen-units = 1
strip = true
split-debuginfo = "packed"
panic = "abort"

[workspace.dependencies]
jeb-common = { version = "0.0.0-dev-2025-12-26.7705", path = "crates/jeb-common" }
jeb-stream = { version = "0.0.0-dev-2025-12-26.7705", path = "crates/jeb-stream" }
jeb-value = { version = "0.0.0-dev-2025-12-26.7705", path = "crates/jeb-value" }
async-stream = "0.3.6"
cfg-if = "1.0.4"
color-eyre = "0.6.5"
derive_more = "2.0.1"
document-features = "0.2.12"
dotenv = "0.15.0"
futures = "0.3.0"
getset = "0.1.6"
ignorable = "0.1.2"
indexmap = "2.0.0"
js-sys = "0.3.82"
macro_rules_attribute = "0.2.2"
owo-colors = "4.2.3"
regex = "1.12.2"
serde = "1.0.0"
serde_bytes = "0.11.0"
serde_json = "1.0.0"
static_assertions = "1.1.0"
tap = "1.0.1"
tokio = "1.0.0"
tokio-stream = "0.1.0"
tokio-util = "0.7.17"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
wasm-bindgen = "0.2.105"
web-sys = "0.3.82"
bstr = "0.2.17"
clap = "3.2.8"
once_cell = "1.13.0"
num-integer = "0.1.45"
itertools = "0.10.3"
pathdiff = "0.2.0"
anyhow = "1.0.0"
sha-1 = "0.10.0"
toml_edit = "0.22.0"
sha1-checked = "0.10.0"
serde_yaml = "0.9.34"
petgraph = "0.6.2"
fast_hilbert = "2.0.2"
parking_lot = "0.12.1"
home = "0.5.3"
digest = "0.10.3"
eyre = "0.6.8"
thiserror = "2.0.0"
glob = "0.3.0"
tracing-error = "0.2.0"
git2 = "0.14.4"
thousands = "0.2.0"
num_cpus = "1.13.1"
proc-macro2 = "1.0.40"
tempfile = "3.3.0"
dissimilar = "1.0.4"
expect-test = { version = "1.4.0", git = "https://github.com/jeremyBanks/expect-test", rev = "bf056e6c5cd3baed9ad2ef3d30bc06dad2778089" }
semver = "1.0.0"
num-traits = "0.2.15"
jeb = { path = "crates/jeb", default-features = false }
