#!/bin/bash
# A wrapper around `cargo run`-like behavior, but falling back to existing
# builds or system installations of tools, if we aren't able to (re)build a
# local copy. This is to mitigate the pain of self-hosting tools inside of our
# own workspace, where changes we're making might break our ability to build
# the tools we want to use while continuing to work on fixing that code!
#
# Therefore any binary inside this workspace that we're running as part of our
# _workflow_ (not for the sake of developing/testing them, but to use them for
# their intended purpose) should be run through `./run <command> <args...>`
# instead of `cargo run --bin <command> -- <args...>`. For example, we may want
# to `./run _autofix` and `./run save`.

set -euo pipefail
declare command="$1"
shift
declare bin=""

declare -r warning=$'\033[1;33mWARNING:\033[0m'
declare -r error=$'\033[1;31mERROR:\033[0m'

if ! cargo build --bin "$command"; then
    echo >&2 "${warning} Failed to build \`${command}\`. Falling back to existing debug build."
fi

if [ -x "./target/debug/$command" ]; then
    bin="./target/debug/$command"
elif [ -x "./target/release/$command" ]; then
    echo >&2 "${warning} Existing debug build not found. Falling back to release build."
    bin="./target/release/$command"
else
    echo >&2 "${warning} Existing builds not found. Falling back to \`cargo install\`ed binary."

    if [ -x "$HOME/.cargo/bin/$command" ]; then
        bin="$HOME/.cargo/bin/$command"
    else
        echo >&2 "${warning} \`cargo install\`ed binary not found for \`${command}\`. Falling back to any existing binary or alias."

        if type "$command" >/dev/null 2>&1; then
            bin="$(type -p "$command")"
        else
            echo >&2 "${error} No existing binary or alias found for \`${command}\`. Giving up."
            exit 1
        fi
    fi
fi

"$bin" "$@"
