[package]
edition = "2018"

name = "speedruns"
version = "0.21.6-dev"

license = "MIT"
repository = "https://github.com/jeremybanks/speedruns"
authors = ["Jeremy Banks <_@jeremy.ca>"]
description = "Unofficial tools for mirroring speedrun.com API data"

autobins = false
categories = []
keywords = []

[lib]
name = "speedruns"
path = "src/lib/speedruns.rs"

[[bin]]
name = "speedruns"
path = "src/bin/speedruns.rs"

[dependencies]
actix-rt.workspace = true
anyhow.workspace = true
argh.workspace = true
async-std = { workspace = true, features = ["attributes"] }
speedruns_api.workspace = true
speedruns_cli.workspace = true
speedruns_database.workspace = true
speedruns_juniper.workspace = true
speedruns_models.workspace = true
speedruns_utils.workspace = true

[workspace]
