[package]
name = "jeb-common"
publish = true
description = "(part of https://crates.io/crates/jeb)"
keywords = []
categories = []
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["wasm"]
wasm = ["dep:wasm-bindgen"]

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
document-features = "0.2.12"
indexmap = { version = "2.0" }
wasm-bindgen = { workspace = true, optional = true }
