[package]
name = "slop"
version.workspace = true
publish.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "slop"
path = "src/lib.rs"

[[bin]]
name = "slop"
path = "src/main.rs"

[dependencies]
json-encoded-binary = { path = "../json-encoded-binary" }
serde.workspace = true
serde_json.workspace = true
indexmap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true
async-stream.workspace = true
clap.workspace = true
color-eyre.workspace = true
rusqlite.workspace = true

[dev-dependencies]
tokio-test.workspace = true
