use anyhow::{Context, Result};
use serde::Serialize;
use std::collections::HashMap;
use std::fs;

#[derive(Serialize)]
struct Workflow {
    #[serde(skip_serializing_if = "Option::is_none")]
    permissions: Option<HashMap<String, String>>,
    on: WorkflowTriggers,
    jobs: HashMap<String, Job>,
}

#[derive(Serialize)]
struct WorkflowTriggers {
    #[serde(skip_serializing_if = "Option::is_none")]
    workflow_dispatch: Option<serde_yaml::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pull_request: Option<serde_yaml::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    push: Option<PushTrigger>,
}

#[derive(Serialize)]
struct PushTrigger {
    branches: Vec<String>,
}

#[derive(Serialize)]
struct Job {
    #[serde(rename = "runs-on")]
    runs_on: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    needs: Option<Vec<String>>,
    steps: Vec<Step>,
}

#[derive(Serialize)]
#[serde(untagged)]
enum Step {
    Action {
        uses: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        with: Option<HashMap<String, String>>,
    },
    Run {
        run: String,
    },
}

pub fn generate_all() -> Result<()> {
    println!("==> Generating GitHub Actions workflows");

    generate_build_workflow()?;

    println!("✓ All workflows generated");
    Ok(())
}

fn generate_build_workflow() -> Result<()> {
    let mut permissions = HashMap::new();
    permissions.insert("contents".to_string(), "read".to_string());

    let mut rustflags = HashMap::new();
    rustflags.insert("rustflags".to_string(), "".to_string());

    let workflow = Workflow {
        permissions: Some(permissions),
        on: WorkflowTriggers {
            workflow_dispatch: Some(serde_yaml::Value::Null),
            pull_request: Some(serde_yaml::Value::Null),
            push: Some(PushTrigger {
                branches: vec!["trunk".to_string()],
            }),
        },
        jobs: {
            let mut jobs = HashMap::new();

            // Build job
            jobs.insert("build".to_string(), Job {
                runs_on: "ubuntu-latest".to_string(),
                needs: None,
                steps: vec![
                    Step::Action {
                        uses: "actions/checkout@v5".to_string(),
                        with: None,
                    },
                    Step::Action {
                        uses: "actions-rust-lang/setup-rust-toolchain@v1".to_string(),
                        with: Some(rustflags.clone()),
                    },
                    Step::Run {
                        run: "cargo run --bin _ci build".to_string(),
                    },
                ],
            });

            // Build warnings job
            jobs.insert("build-warnings".to_string(), Job {
                runs_on: "ubuntu-latest".to_string(),
                needs: Some(vec!["build".to_string()]),
                steps: vec![
                    Step::Action {
                        uses: "actions/checkout@v5".to_string(),
                        with: None,
                    },
                    Step::Action {
                        uses: "actions-rust-lang/setup-rust-toolchain@v1".to_string(),
                        with: Some(rustflags.clone()),
                    },
                    Step::Run {
                        run: "cargo run --bin _ci build-warnings".to_string(),
                    },
                ],
            });

            jobs
        },
    };

    let yaml = serde_yaml::to_string(&workflow)
        .context("Failed to serialize workflow to YAML")?;

    // Add header comment warning not to edit manually
    let header = "# DO NOT EDIT - Generated by `cargo run --bin _ci generate-workflows`\n# Edit crates/_ci/src/workflows.rs instead\n\n";
    let content = format!("{}{}", header, yaml);

    let path = ".github/workflows/build.yml";
    fs::write(path, content)
        .with_context(|| format!("Failed to write {}", path))?;

    println!("  Generated {}", path);
    Ok(())
}
