[package]
name = "json-encoded-binary"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nom.workspace = true
# TODO: Use nom-supreme for better error messages and combinators
nom-supreme.workspace = true
# TODO: Use nom-locate for error position tracking
nom-locate.workspace = true
