[package]
name = "git-zoom"
publish = false
description = "git zoom in; git zoom out"
keywords = []
categories = []
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dev-dependencies]
tempfile = "3"

[dependencies]
git2 = "0.20.3"
sha1-checked = { version = "0.10.0", default-features = true, features = ["std"]}
