[package]
name = "jeb-bi"
publish = true
description = "(part of https://crates.io/crates/jeb)"
keywords = []
categories = []
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
wasm = ["dep:wasm-bindgen"]

[dependencies]
jeb-common = { workspace = true }

derive_more = { workspace = true, features = ["full"] }
document-features = { workspace = true }
indexmap = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
fast_hilbert = "2.0.2"
