[package]
name = "ideated-encoding-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.ideated-encoding]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_encoding"
path = "fuzz_targets/fuzz_encoding.rs"
test = false
doc = false
bench = false
