[package]
name = "ideated-encoding-fuzz"
version = "0.0.0"
edition.workspace = true
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys.workspace = true
ideated-encoding = { path = ".." }

[[bin]]
name = "fuzz_encoding"
path = "fuzz_targets/fuzz_encoding.rs"
test = false
doc = false
bench = false
