#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit extglob nullglob compat"${BASH_COMPAT=42}"
trap 'kill $(jobs -p) 2>/dev/null' EXIT

./build

http-server \
  -d=false \
  -c=8 \
  ''./stadia.run/'' \
  --port 57481 &

http-server \
  -d=false \
  -c=8 \
  ''./stadia.st/'' \
  --port 57483 &

HOST=dev-api.stadia.st PORT=57482 \
  ./dev-api.rb &

sleep 1
echo

echo "  $(tput smul && tput setaf 6 || :)http://localhost:57481/$(tput sgr0 || :)"
echo
echo "  $(tput smul && tput setaf 6 || :)http://localhost:57482/records.json$(tput sgr0 || :)"
echo
echo "  $(tput smul && tput setaf 6 || :)http://localhost:57483/$(tput sgr0 || :)"
echo

(
  sleep 1
  declare output
  output="$(
    /Applications/"Google Chrome.app"/Contents/MacOS/"Google Chrome" \
      --headless \
      --user-data-dir="$HOME"/Library/"Application Support"/Google/Chrome/ \
      'http://dev.stadia.run:57481/?q=cel#dev-tools' 2>&1 \
      | egrep --only-matching '<st-\w+>.*</st-\w+>' -A1 | cat || :)";
  echo
  if echo "$output" | grep -q '<st-event>load</st-event>'; then
    if echo "$output" | grep -q '<st-error>'; then
      echo "[headless ERROR] errors ocurred before page load:"
      echo "$output" | grep '<st-error>' -A1
      exit 1
    else
      echo "[headless INFO] no errors before page load"
    fi
  else
    echo "[headless WARN] failed to load run headless test (was Chrome busy?)"
  fi
  echo
) &

wait
