[package]
name = "zerodmg"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true
description = "pieces of a naive incomplete broken game boy emulator"
readme = "README.md"
categories = []
keywords = []

[dependencies]
zerodmg-codes.workspace = true
zerodmg-emulator.workspace = true
zerodmg-utils.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["server", "http1"] }
hyper-util = { workspace = true, features = ["tokio"] }
image.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full"] }
