[package]
name = "jeb-streaming"
publish = true
description = "(part of https://crates.io/crates/jeb)"
keywords = []
categories = []
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["json", "serde"]
serde = ["jeb-value/serde", "dep:serde"]
fs = ["tokio/fs"]
json = []
stdio = ["tokio/io-std"]
wasm = ["dep:wasm-bindgen", "jeb-value/wasm", "jeb-common/wasm"]

[dependencies]
jeb-value = { workspace = true }
jeb-common = { workspace = true }
derive_more = { version = "2.0.1", features = ["full"] }

tokio = { version = "1.0", features = ["rt", "macros", "sync", "io-util"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7.17", features = ["codec", "io"] }
wasm-bindgen = { workspace = true, optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
static_assertions = "1.1.0"
macro_rules_attribute = "0.2.2"
async-stream = "0.3.6"
futures = "0.3.31"
cfg-if = "1.0.4"
document-features = "0.2.12"

fuckit = "*"