[package]
name = "jeb"
publish = true
description = "experimenting with machine- and human-sympathetic encoding"
keywords = ["encoding"]
categories = ["encoding"]
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "jeb"
path = "src/lib.rs"

[[bin]]
name = "jeb"
path = "src/bin/jeb.rs"

[features]
default = ["bin", "fs", "stdio"]
wasm = ["dep:wasm-bindgen", "dep:js-sys", "dep:web-sys", "jeb-value/wasm"]
bin = [
    "fs",
    "stdio",
    "dep:color-eyre",
    "dep:dotenv",
    "dep:owo-colors",
    "tracing-subscriber/env-filter",
]

fs = ["tokio/fs"]
stdio = ["tokio/io-std"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.signing]
algorithm = "minisign"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
futures = "0.3"
getset = "0.1.6"
indexmap = { version = "2.0", features = ["serde"] }
regex = "1.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tap = "1.0.1"
tokio = { version = "1.0", features = ["rt", "macros", "sync", "io-util"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7.17", features = ["codec", "io"] }
tracing = "0.1.43"

jeb-value = { workspace = true, features = ["serde"] }
jeb-streaming = { workspace = true }
jeb-common = { workspace = true }

color-eyre = { version = "0.6.5", optional = true }
dotenv = { version = "0.15.0", optional = true }
js-sys = { version = "0.3.82", optional = true }
owo-colors = { version = "4.2.3", optional = true }
tracing-subscriber = { version = "0.3.22", optional = true }
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }
ignorable = "0.1.2"
document-features = "0.2.12"
