[package]
name = "jeb"
publish = true
repository = "https://github.com/jeremyBanks/jeb"
description = "experimenting with machine- and human-sympathetic encoding"
keywords = ["encoding"]
categories = ["encoding"]
version.workspace = true
license.workspace = true
edition.workspace = true
exclude.workspace = true

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
dotenv = "0.15.0"
futures.workspace = true
indexmap = { version = "2.0", features = ["serde"] }
owo-colors = "4.2.3"
parking_lot = "0.12.5"
serde.workspace = true
serde_json.workspace = true
tap = "1.0.1"
tokio = { version = "1.0", features = ["rt", "macros", "sync", "fs", "io-std", "io-util"] }
tokio-stream.workspace = true
tokio-util = { version = "0.7.17", features = ["codec", "io"] }

[lib]

[[bin]]
name = "jeb"
path = "src/bin/jeb.rs"
