[package]
name = "jeb-wasm"
publish = true
description = "(part of https://crates.io/crates/jeb)"
keywords = []
categories = []
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lib]
name = "jeb"
crate-type = ["cdylib"]
doc = false

[dependencies]
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }

document-features = "0.2.12"
jeb = { workspace = true, features = ["wasm"] }

