[package]
name = "jeb-stream"
publish = true
description = "(part of https://crates.io/crates/jeb)"
keywords = []
categories = []
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []
serde = ["jeb-value/serde", "dep:serde"]
fs = ["tokio/fs"]
json = []
stdio = ["tokio/io-std"]
wasm = ["dep:wasm-bindgen", "jeb-value/wasm", "jeb-common/wasm"]

[dependencies]
async-stream = { workspace = true }
cfg-if = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
document-features = { workspace = true }
futures = { workspace = true }
macro_rules_attribute = { workspace = true }
parking_lot = "0.12"
serde = { workspace = true, optional = true, features = ["derive"] }
static_assertions = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "sync", "io-util"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true, features = ["codec", "io"] }
wasm-bindgen = { workspace = true, optional = true }

jeb-common = { workspace = true }
jeb-value = { workspace = true }