[package]
name = "json-encoded-binary"
version.workspace = true
publish = false
license.workspace = true
edition.workspace = true
exclude = [
    "*.md",
    "!README.md",
]


[dependencies]
nom.workspace = true
nom-supreme.workspace = true
nom_locate.workspace = true
static_assertions = "1.1.0"
winnow.workspace = true
