[package]
default-run = "save"
description = "Would you like to SAVE the change?"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "save"
version = "0.20220708.0"
repository.workspace = true
categories = []
keywords = []

[dependencies]
tracing = { version = "0.1.43", features = ["log"] }
color-eyre.workspace = true
bstr = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "cargo", "unicode", "wrap_help"] }
digest = { workspace = true }
dissimilar = { workspace = true }
expect-test = { workspace = true }
eyre = { workspace = true }
git2 = { workspace = true }
home = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
num-integer = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
petgraph = { workspace = true }
proc-macro2 = { workspace = true }
regex = { workspace = true }
sha-1 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
thousands = { workspace = true }
tracing-error = { workspace = true, features = ["traced-error"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[package.metadata.release]
allow-branch = ["trunk"]
post-release-commit-message = "v{{next_version}}"
pre-release-commit-message = "v{{version}}"
tag-message = "https://crates.io/crates/{{crate_name}}/{{version}}"
tag-name = "{{version}}"
