[package]
name = "_trace"
version = "0.1.0"
edition = "2021"
description = "A language-agnostic requirements tracking tool"
license = "MIT OR Apache-2.0"
publish = false
repository.workspace = true
categories = []
keywords = []

[dependencies]
clap = { version = "4", features = ["derive"] }
ignore.workspace = true
regex.workspace = true
