[package]
name = "_scripts"
publish = false
description = ""
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
categories = []
keywords = []

[dependencies]
jeb-tracing.workspace = true
_chosen.workspace = true
anyhow.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
glob.workspace = true
pathdiff.workspace = true
rand.workspace = true
semver.workspace = true
serde_json.workspace = true
sha-1.workspace = true
tokio.workspace = true
toml_edit.workspace = true

[dev-dependencies]
serde_yaml.workspace = true
tempfile.workspace = true
