[package]
name = "jeb-bytes-as-text"
publish = true
description.workspace = true
keywords = []
categories = []
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
jeb-common.workspace = true

[features]
default = []
