on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_TOKEN }}
      - id: commit-info
        run: |
          MESSAGE=$(git log -1 --pretty=%s)
          AUTHOR=$(git log -1 --pretty="%an <%ae>")
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT
          if [[ "$MESSAGE" == "autofix autofix autofix"* ]]; then
            echo "ERROR: Autofix has already run 3 times in a row, aborting to prevent infinite loop"
            exit 1
          fi
      - uses: denoland/setup-deno@v2
      - run: deno fmt
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fix --allow-dirty
      - run: cargo clippy --fix --allow-dirty
      - run: cargo fmt
      - run: crates/jeb/examples/all.sh
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: autofix ${{ steps.commit-info.outputs.message }}
          commit_author: ${{ steps.commit-info.outputs.author }}
