on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
    steps:
      - id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: denoland/setup-deno@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: deno fmt
      - run: cargo fix --allow-dirty
      - run: cargo clippy --fix --allow-dirty
      - run: cargo fmt
      - run: deno task wasmbuild
      - run: crates/jeb/examples/all.sh
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: autofix
          commit_author: ${{ steps.last-commit.outputs.author }}
