name: Version Check

on:
  push:
    branches: [ main, master, trunk ]
  pull_request:

jobs:
  check-version:
    name: Validate Version is 0.0.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Check version
        run: ./scripts/check-version.sh
