[package]
name = "serde-value"
description = "Complete in-memory representation of the serde data model"
publish = false
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
arbitrary = ["dep:arbitrary"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
arbitrary = { version = "1", optional = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
arbitrary = { version = "1" }
bincode = "1"
rmp-serde = "1"
toml = "0.8"
ron = "0.8"
postcard = { version = "1", features = ["alloc"] }
